<?xml version="1.0" encoding="utf-8"?>
<test-run id="2" name="Reflection.Randomness.exe" fullname="C:/Users/Daniil/Desktop/C#/ООП С#/лабы/Случайные объекты/bin/Debug/Reflection.Randomness.exe" testcasecount="6" result="Failed" start-time="2023-12-06 17:22:34Z" end-time="2023-12-06 17:22:34Z" duration="0.285245" total="6" passed="4" failed="2" inconclusive="0" skipped="0" asserts="5" random-seed="264488880">
  <command-line><![CDATA["C:\Users\Daniil\Desktop\C#\ООП С#\лабы\Случайные объекты\bin\Debug\Reflection.Randomness.exe"   ]]></command-line>
  <filter />
  <test-suite type="Assembly" id="1007" name="Reflection.Randomness.exe" fullname="C:/Users/Daniil/Desktop/C#/ООП С#/лабы/Случайные объекты/bin/Debug/Reflection.Randomness.exe" runstate="Runnable" testcasecount="6" result="Failed" site="Child" start-time="2023-12-06 17:22:34Z" end-time="2023-12-06 17:22:34Z" duration="0.285245" total="6" passed="4" failed="2" warnings="0" inconclusive="0" skipped="0" asserts="5">
    <environment framework-version="3.6.0.0" clr-version="4.0.30319.42000" os-version="Microsoft Windows NT 6.2.9200.0" platform="Win32NT" cwd="C:\Users\Daniil\Desktop\C#\ООП С#\лабы\Случайные объекты\bin\Debug" machine-name="DESKTOP-SU09UBG" user="Daniil" user-domain="DESKTOP-SU09UBG" culture="ru-RU" uiculture="ru-RU" os-architecture="x86" />
    <settings>
      <setting name="WorkDirectory" value="C:\Users\Daniil\Desktop\C#\ООП С#\лабы\Случайные объекты\bin\Debug" />
      <setting name="NumberOfTestWorkers" value="12" />
    </settings>
    <properties>
      <property name="_PID" value="28916" />
      <property name="_APPDOMAIN" value="Reflection.Randomness.exe" />
    </properties>
    <failure>
      <message><![CDATA[One or more child tests had errors]]></message>
    </failure>
    <test-suite type="TestSuite" id="1008" name="Reflection" fullname="Reflection" runstate="Runnable" testcasecount="6" result="Failed" site="Child" start-time="2023-12-06 17:22:34Z" end-time="2023-12-06 17:22:34Z" duration="0.253991" total="6" passed="4" failed="2" warnings="0" inconclusive="0" skipped="0" asserts="5">
      <failure>
        <message><![CDATA[One or more child tests had errors]]></message>
      </failure>
      <test-suite type="TestSuite" id="1009" name="Randomness" fullname="Reflection.Randomness" runstate="Runnable" testcasecount="6" result="Failed" site="Child" start-time="2023-12-06 17:22:34Z" end-time="2023-12-06 17:22:34Z" duration="0.222384" total="6" passed="4" failed="2" warnings="0" inconclusive="0" skipped="0" asserts="5">
        <failure>
          <message><![CDATA[One or more child tests had errors]]></message>
        </failure>
        <test-suite type="TestFixture" id="1000" name="Generator_should" fullname="Reflection.Randomness.Generator_should" classname="Reflection.Randomness.Generator_should" runstate="Runnable" testcasecount="6" result="Failed" site="Child" start-time="2023-12-06 17:22:34Z" end-time="2023-12-06 17:22:34Z" duration="0.191161" total="6" passed="4" failed="2" warnings="0" inconclusive="0" skipped="0" asserts="5">
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-case id="1006" name="FailWithInformativeMessage_WhenAttributeUsedWithWrongDistributionType" fullname="Reflection.Randomness.Generator_should.FailWithInformativeMessage_WhenAttributeUsedWithWrongDistributionType" methodname="FailWithInformativeMessage_WhenAttributeUsedWithWrongDistributionType" classname="Reflection.Randomness.Generator_should" runstate="Runnable" seed="1761345628" result="Passed" start-time="2023-12-06 17:22:34Z" end-time="2023-12-06 17:22:34Z" duration="0.004822" asserts="1" />
          <test-case id="1005" name="FailWithInformativeMessage_WhenAttributeUsedWithWrongNumberOfArguments" fullname="Reflection.Randomness.Generator_should.FailWithInformativeMessage_WhenAttributeUsedWithWrongNumberOfArguments" methodname="FailWithInformativeMessage_WhenAttributeUsedWithWrongNumberOfArguments" classname="Reflection.Randomness.Generator_should" runstate="Runnable" seed="1921308569" result="Passed" start-time="2023-12-06 17:22:34Z" end-time="2023-12-06 17:22:34Z" duration="0.000183" asserts="1" />
          <test-case id="1001" name="GenerateT1" fullname="Reflection.Randomness.Generator_should.GenerateT1" methodname="GenerateT1" classname="Reflection.Randomness.Generator_should" runstate="Runnable" seed="1455705041" result="Passed" start-time="2023-12-06 17:22:34Z" end-time="2023-12-06 17:22:34Z" duration="0.005652" asserts="1" />
          <test-case id="1003" name="GenerateT2" fullname="Reflection.Randomness.Generator_should.GenerateT2" methodname="GenerateT2" classname="Reflection.Randomness.Generator_should" runstate="Runnable" seed="1631645354" result="Failed" label="Error" start-time="2023-12-06 17:22:34Z" end-time="2023-12-06 17:22:34Z" duration="0.011953" asserts="0">
            <failure>
              <message><![CDATA[System.InvalidOperationException : Последовательность не содержит элементов]]></message>
              <stack-trace><![CDATA[   в System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   в Reflection.Randomness.Generator`1..ctor() в C:\Users\Daniil\Desktop\C#\ООП С#\лабы\Случайные объекты\Generator.cs:строка 22
   в Reflection.Randomness.Generator_should.GenerateT2() в C:\Users\Daniil\Desktop\C#\ООП С#\лабы\Случайные объекты\Generator_should.cs:строка 78]]></stack-trace>
            </failure>
          </test-case>
          <test-case id="1002" name="GiveUniqueResults_OnEveryGenerateRun" fullname="Reflection.Randomness.Generator_should.GiveUniqueResults_OnEveryGenerateRun" methodname="GiveUniqueResults_OnEveryGenerateRun" classname="Reflection.Randomness.Generator_should" runstate="Runnable" seed="1442984621" result="Passed" start-time="2023-12-06 17:22:34Z" end-time="2023-12-06 17:22:34Z" duration="0.003347" asserts="2" />
          <test-case id="1004" name="PerformanceTest" fullname="Reflection.Randomness.Generator_should.PerformanceTest" methodname="PerformanceTest" classname="Reflection.Randomness.Generator_should" runstate="Runnable" seed="1190006352" result="Failed" label="Error" start-time="2023-12-06 17:22:34Z" end-time="2023-12-06 17:22:34Z" duration="0.000669" asserts="0">
            <failure>
              <message><![CDATA[System.InvalidOperationException : Последовательность не содержит элементов]]></message>
              <stack-trace><![CDATA[   в System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   в Reflection.Randomness.Generator`1..ctor() в C:\Users\Daniil\Desktop\C#\ООП С#\лабы\Случайные объекты\Generator.cs:строка 22
   в Reflection.Randomness.Generator_should.PerformanceTest() в C:\Users\Daniil\Desktop\C#\ООП С#\лабы\Случайные объекты\Generator_should.cs:строка 91]]></stack-trace>
            </failure>
          </test-case>
        </test-suite>
      </test-suite>
    </test-suite>
  </test-suite>
</test-run>